/**
 * All 50 base cards for Madness Rumble Space
 *
 * Distribution:
 * - 25 Common
 * - 15 Rare
 * - 7 Epic
 * - 3 Legendary
 */

import { CardRarity, CardType } from '@prisma/client';

export interface CardDefinition {
  name: string;
  type: CardType;
  rarity: CardRarity;
  cost: number;
  attack?: number;
  health?: number;
  effect?: string;
  effectCode: string; // Unique identifier for game logic
  heroEffects?: Record<string, string>; // Hero-specific effects
  flavorText?: string;
  set: string;
  imageUrl?: string;
}

export const CARDS: CardDefinition[] = [
  // ==========================================
  // UNIVERSAL CREATURES (15 cards)
  // ==========================================
  {
    name: 'Space Rookie',
    type: 'CREATURE',
    rarity: 'COMMON',
    cost: 2,
    attack: 2,
    health: 2,
    effectCode: 'NONE',
    flavorText: 'Fresh out of the academy and eager to prove themselves.',
    set: 'base',
    imageUrl: '/cards/space-rookie.png',
  },
  {
    name: 'Asteroid Miner',
    type: 'CREATURE',
    rarity: 'COMMON',
    cost: 2,
    attack: 1,
    health: 3,
    effect: 'When summoned: Draw 1 card',
    effectCode: 'DRAW_ON_SUMMON',
    flavorText: 'Always finds something valuable in the debris.',
    set: 'base',
    imageUrl: '/cards/asteroid-miner.png',
  },
  {
    name: 'Cosmic Scout',
    type: 'CREATURE',
    rarity: 'COMMON',
    cost: 1,
    attack: 1,
    health: 1,
    effect: 'First Strike',
    effectCode: 'FIRST_STRIKE',
    flavorText: 'Fast and deadly.',
    set: 'base',
    imageUrl: '/cards/cosmic-scout.png',
  },
  {
    name: 'Nebula Guardian',
    type: 'CREATURE',
    rarity: 'COMMON',
    cost: 3,
    attack: 2,
    health: 4,
    effect: 'Taunt - Enemy creatures must attack this first',
    effectCode: 'TAUNT',
    flavorText: 'An immovable object in the void.',
    set: 'base',
    imageUrl: '/cards/nebula-guardian.png',
  },
  {
    name: 'Void Crawler',
    type: 'CREATURE',
    rarity: 'COMMON',
    cost: 4,
    attack: 4,
    health: 3,
    effectCode: 'NONE',
    flavorText: 'It hungers for the light of stars.',
    set: 'base',
    imageUrl: '/cards/void-crawler.png',
  },
  {
    name: 'Mercenary Veteran',
    type: 'CREATURE',
    rarity: 'RARE',
    cost: 3,
    attack: 3,
    health: 3,
    effect: 'Cannot be targeted by spells',
    effectCode: 'SPELL_IMMUNE',
    flavorText: 'Seen it all, survived it all.',
    set: 'base',
    imageUrl: '/cards/mercenary-veteran.png',
  },
  {
    name: 'Plasma Elemental',
    type: 'CREATURE',
    rarity: 'RARE',
    cost: 4,
    attack: 3,
    health: 4,
    effect: 'When this attacks: Deal 1 damage to all other creatures',
    effectCode: 'AOE_ON_ATTACK',
    flavorText: 'Pure energy given form.',
    set: 'base',
    imageUrl: '/cards/plasma-elemental.png',
  },
  {
    name: 'Orbital Striker',
    type: 'CREATURE',
    rarity: 'RARE',
    cost: 5,
    attack: 5,
    health: 3,
    effect: 'First Strike',
    effectCode: 'FIRST_STRIKE',
    flavorText: 'Strikes from orbit. No survivors.',
    set: 'base',
    imageUrl: '/cards/orbital-striker.png',
  },
  {
    name: 'Cosmic Golem',
    type: 'CREATURE',
    rarity: 'EPIC',
    cost: 5,
    attack: 5,
    health: 5,
    effect: 'Costs 1 less for each creature you control',
    effectCode: 'COST_REDUCTION_PER_CREATURE',
    flavorText: 'Assembled from the debris of fallen ships.',
    set: 'base',
    imageUrl: '/cards/cosmic-golem.png',
  },
  {
    name: 'Star Devourer',
    type: 'CREATURE',
    rarity: 'EPIC',
    cost: 6,
    attack: 4,
    health: 6,
    effect: 'When this attacks: Restore 2 health to your hero',
    effectCode: 'LIFESTEAL',
    flavorText: 'It feeds on light itself.',
    set: 'base',
    imageUrl: '/cards/star-devourer.png',
  },
  {
    name: 'Galactic Leviathan',
    type: 'CREATURE',
    rarity: 'LEGENDARY',
    cost: 8,
    attack: 8,
    health: 8,
    effect: 'When summoned: Destroy all other creatures',
    effectCode: 'BOARD_CLEAR_ON_SUMMON',
    flavorText: 'When it arrives, everything else dies.',
    set: 'base',
    imageUrl: '/cards/galactic-leviathan.png',
  },
  {
    name: 'Quantum Mimic',
    type: 'CREATURE',
    rarity: 'COMMON',
    cost: 2,
    attack: 1,
    health: 2,
    effect: 'When summoned: Copy stats of target creature',
    effectCode: 'COPY_STATS',
    flavorText: 'Identity is flexible in quantum space.',
    set: 'base',
    imageUrl: '/cards/quantum-mimic.png',
  },
  {
    name: 'Shield Drone',
    type: 'CREATURE',
    rarity: 'COMMON',
    cost: 1,
    attack: 0,
    health: 3,
    effect: 'Taunt',
    effectCode: 'TAUNT',
    flavorText: 'Standard issue. Effective.',
    set: 'base',
    imageUrl: '/cards/shield-drone.png',
  },
  {
    name: 'Scrap Collector',
    type: 'CREATURE',
    rarity: 'RARE',
    cost: 3,
    attack: 2,
    health: 3,
    effect: 'When a creature dies: This gains +1/+1',
    effectCode: 'GROW_ON_DEATH',
    flavorText: 'One being\'s trash is another\'s upgrade.',
    set: 'base',
    imageUrl: '/cards/scrap-collector.png',
  },
  {
    name: 'Warp Stalker',
    type: 'CREATURE',
    rarity: 'EPIC',
    cost: 4,
    attack: 3,
    health: 2,
    effect: 'Cannot be blocked by creatures with 2 or less attack',
    effectCode: 'EVASION',
    flavorText: 'Phases through weaker defenses.',
    set: 'base',
    imageUrl: '/cards/warp-stalker.png',
  },

  // ==========================================
  // UNIVERSAL SPELLS (12 cards)
  // ==========================================
  {
    name: 'Laser Blast',
    type: 'SPELL',
    rarity: 'COMMON',
    cost: 1,
    effect: 'Deal 3 damage to target creature or hero',
    effectCode: 'DAMAGE_3',
    flavorText: 'Precision. Lethality. Simplicity.',
    set: 'base',
    imageUrl: '/cards/laser-blast.png',
  },
  {
    name: 'Shield Generator',
    type: 'SPELL',
    rarity: 'COMMON',
    cost: 1,
    effect: 'Give a creature +0/+4 health',
    effectCode: 'BUFF_HEALTH_4',
    flavorText: 'Deploy shields!',
    set: 'base',
    imageUrl: '/cards/shield-generator.png',
  },
  {
    name: 'Tactical Retreat',
    type: 'SPELL',
    rarity: 'RARE',
    cost: 2,
    effect: 'Return a creature to your hand. Draw 1 card.',
    effectCode: 'BOUNCE_DRAW',
    flavorText: 'Live to fight another day.',
    set: 'base',
    imageUrl: '/cards/tactical-retreat.png',
  },
  {
    name: 'Cosmic Flux',
    type: 'SPELL',
    rarity: 'COMMON',
    cost: 2,
    effect: 'Draw 2 cards',
    effectCode: 'DRAW_2',
    flavorText: 'Knowledge flows through the cosmos.',
    set: 'base',
    imageUrl: '/cards/cosmic-flux.png',
  },
  {
    name: 'Meteor Strike',
    type: 'SPELL',
    rarity: 'EPIC',
    cost: 5,
    effect: 'Deal 5 damage to all creatures',
    effectCode: 'AOE_DAMAGE_5',
    flavorText: 'Call down the rocks.',
    set: 'base',
    imageUrl: '/cards/meteor-strike.png',
  },
  {
    name: 'Vaporize',
    type: 'SPELL',
    rarity: 'RARE',
    cost: 3,
    effect: 'Destroy target creature',
    effectCode: 'DESTROY_CREATURE',
    flavorText: 'Gone in an instant.',
    set: 'base',
    imageUrl: '/cards/vaporize.png',
  },
  {
    name: 'Emergency Repairs',
    type: 'SPELL',
    rarity: 'COMMON',
    cost: 2,
    effect: 'Restore 5 health to your hero or a creature',
    effectCode: 'HEAL_5',
    flavorText: 'Patch it up, move it out.',
    set: 'base',
    imageUrl: '/cards/emergency-repairs.png',
  },
  {
    name: 'Overcharge',
    type: 'SPELL',
    rarity: 'RARE',
    cost: 2,
    effect: 'Give a creature +3/+0 this turn',
    effectCode: 'BUFF_ATTACK_3_TEMP',
    flavorText: 'Maximum power!',
    set: 'base',
    imageUrl: '/cards/overcharge.png',
  },
  {
    name: 'Time Warp',
    type: 'SPELL',
    rarity: 'LEGENDARY',
    cost: 7,
    effect: 'Take an extra turn after this one',
    effectCode: 'EXTRA_TURN',
    flavorText: 'Bend time itself to your will.',
    set: 'base',
    imageUrl: '/cards/time-warp.png',
  },
  {
    name: 'Neural Disruption',
    type: 'SPELL',
    rarity: 'RARE',
    cost: 3,
    effect: 'Target creature cannot attack next turn',
    effectCode: 'STUN',
    flavorText: 'Scramble their circuits.',
    set: 'base',
  },
  {
    name: 'Gravity Well',
    type: 'SPELL',
    rarity: 'EPIC',
    cost: 4,
    effect: 'Return all creatures to their owner\'s hands',
    effectCode: 'BOUNCE_ALL',
    flavorText: 'Reset the battlefield.',
    set: 'base',
  },
  {
    name: 'Adrenaline Surge',
    type: 'SPELL',
    rarity: 'COMMON',
    cost: 1,
    effect: 'Give a creature +2/+2',
    effectCode: 'BUFF_2_2',
    flavorText: 'Push beyond limits.',
    set: 'base',
  },

  // ==========================================
  // EQUIPMENTS (8 cards)
  // ==========================================
  {
    name: 'Plasma Blade',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    cost: 2,
    effect: '+2/+0. Equipped creature has First Strike',
    effectCode: 'EQUIP_ATTACK_2_FIRST_STRIKE',
    flavorText: 'Cut through anything.',
    set: 'base',
    imageUrl: '/cards/plasma-blade.png',
  },
  {
    name: 'Energy Shield',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    cost: 2,
    effect: '+0/+3. Equipped creature cannot be destroyed by spells',
    effectCode: 'EQUIP_HEALTH_3_SPELL_IMMUNE',
    flavorText: 'Deflect the unexpected.',
    set: 'base',
  },
  {
    name: 'Gravity Hammer',
    type: 'EQUIPMENT',
    rarity: 'EPIC',
    cost: 3,
    effect: '+3/+0. When this creature attacks: Stun target creature',
    effectCode: 'EQUIP_ATTACK_3_STUN',
    flavorText: 'Crushing force.',
    set: 'base',
  },
  {
    name: 'Jetpack Booster',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    cost: 1,
    effect: '+1/+1. Equipped creature has Evasion',
    effectCode: 'EQUIP_1_1_EVASION',
    flavorText: 'Fly over obstacles.',
    set: 'base',
  },
  {
    name: 'Nano Armor',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    cost: 3,
    effect: '+0/+4. When this creature takes damage: Restore 2 health to it',
    effectCode: 'EQUIP_HEALTH_4_REGEN',
    flavorText: 'Self-repairing nanobots.',
    set: 'base',
  },
  {
    name: 'Disruption Field',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    cost: 1,
    effect: '+1/+2',
    effectCode: 'EQUIP_1_2',
    flavorText: 'Basic protection.',
    set: 'base',
  },
  {
    name: 'Targeting Computer',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    cost: 2,
    effect: '+2/+0. Equipped creature deals double damage to damaged creatures',
    effectCode: 'EQUIP_ATTACK_2_EXECUTE',
    flavorText: 'Lock on. Fire.',
    set: 'base',
  },
  {
    name: 'Quantum Core',
    type: 'EQUIPMENT',
    rarity: 'LEGENDARY',
    cost: 4,
    effect: '+3/+3. When equipped creature attacks: Deal 2 damage to all enemies',
    effectCode: 'EQUIP_3_3_AOE',
    flavorText: 'Unstable power.',
    set: 'base',
  },

  // ==========================================
  // TRAPS (5 cards)
  // ==========================================
  {
    name: 'Proximity Mine',
    type: 'TRAP',
    rarity: 'COMMON',
    cost: 2,
    effect: 'When opponent plays a creature: Deal 2 damage to it',
    effectCode: 'TRAP_DAMAGE_ON_SUMMON',
    flavorText: 'Step carefully.',
    set: 'base',
    imageUrl: '/cards/proximity-mine.png',
  },
  {
    name: 'EMP Trap',
    type: 'TRAP',
    rarity: 'RARE',
    cost: 3,
    effect: 'When opponent plays a spell: Counter it and draw 1 card',
    effectCode: 'TRAP_COUNTER_SPELL',
    flavorText: 'Magic? Not today.',
    set: 'base',
  },
  {
    name: 'Void Snare',
    type: 'TRAP',
    rarity: 'EPIC',
    cost: 4,
    effect: 'When opponent attacks: Destroy attacking creature',
    effectCode: 'TRAP_DESTROY_ATTACKER',
    flavorText: 'Aggressive enemies fall hardest.',
    set: 'base',
  },
  {
    name: 'Stasis Field',
    type: 'TRAP',
    rarity: 'RARE',
    cost: 3,
    effect: 'When opponent plays a creature: Return it to their hand',
    effectCode: 'TRAP_BOUNCE_CREATURE',
    flavorText: 'Not so fast.',
    set: 'base',
  },
  {
    name: 'Explosive Surprise',
    type: 'TRAP',
    rarity: 'COMMON',
    cost: 1,
    effect: 'When you take damage: Deal 3 damage to enemy hero',
    effectCode: 'TRAP_DAMAGE_ON_HIT',
    flavorText: 'You\'ll regret that.',
    set: 'base',
  },

  // ==========================================
  // HERO-SYNERGY CARDS (10 cards)
  // ==========================================
  {
    name: 'Rocket Fuel',
    type: 'SPELL',
    rarity: 'COMMON',
    cost: 1,
    effect: 'Give a creature +2/+0 this turn',
    effectCode: 'ROCKET_FUEL',
    heroEffects: {
      'jetpack-junkie': 'Give all your creatures +1/+0 this turn',
      'rocket-maniac': 'Deal 3 damage to target creature',
    },
    flavorText: 'Highly volatile. Highly effective.',
    set: 'base',
  },
  {
    name: 'Explosive Round',
    type: 'SPELL',
    rarity: 'RARE',
    cost: 3,
    effect: 'Deal 4 damage to target',
    effectCode: 'EXPLOSIVE_ROUND',
    heroEffects: {
      'rocket-maniac': 'Deal 2 damage to all enemies',
      'sharpshooter': 'Destroy target creature with 5 or less health',
    },
    flavorText: 'Boom.',
    set: 'base',
  },
  {
    name: 'Nano Swarm',
    type: 'SPELL',
    rarity: 'EPIC',
    cost: 4,
    effect: 'Restore 5 health to your hero',
    effectCode: 'NANO_SWARM',
    heroEffects: {
      'bio-healer': 'Restore 5 health to your hero and all creatures',
      'drone-master': 'Summon two 1/1 Nano Drones',
    },
    flavorText: 'Microscopic miracles.',
    set: 'base',
  },
  {
    name: 'Sabotage',
    type: 'SPELL',
    rarity: 'LEGENDARY',
    cost: 4,
    effect: 'Destroy target creature',
    effectCode: 'SABOTAGE',
    heroEffects: {
      'shapeshifter': 'Destroy target creature and copy it to your hand',
      'mine-layer': 'Destroy target creature and set a trap',
    },
    flavorText: 'Internal systems compromised.',
    set: 'base',
  },
  {
    name: 'Thermal Charge',
    type: 'SPELL',
    rarity: 'COMMON',
    cost: 2,
    effect: 'Deal 2 damage',
    effectCode: 'THERMAL_CHARGE',
    heroEffects: {
      'plasma-freak': 'Deal 2 damage. Target burns for 1 damage per turn.',
      'mine-layer': 'Set a mine that deals 3 damage',
    },
    flavorText: 'Hot stuff.',
    set: 'base',
  },
  {
    name: 'Fortify Position',
    type: 'SPELL',
    rarity: 'RARE',
    cost: 2,
    effect: 'Give a creature +0/+3',
    effectCode: 'FORTIFY',
    heroEffects: {
      'tank-brute': 'Give all your creatures +0/+2',
      'drone-master': 'Summon a 0/3 Turret',
    },
    flavorText: 'Dig in and hold.',
    set: 'base',
  },
  {
    name: 'Stealth Protocol',
    type: 'SPELL',
    rarity: 'RARE',
    cost: 3,
    effect: 'Return a creature to your hand',
    effectCode: 'STEALTH',
    heroEffects: {
      'shapeshifter': 'Copy target enemy creature to your hand',
      'jetpack-junkie': 'Return a creature and it costs 1 less',
    },
    flavorText: 'Vanish without a trace.',
    set: 'base',
  },
  {
    name: 'Artillery Strike',
    type: 'SPELL',
    rarity: 'EPIC',
    cost: 5,
    effect: 'Deal 3 damage to all enemy creatures',
    effectCode: 'ARTILLERY',
    heroEffects: {
      'rocket-maniac': 'Deal 4 damage to all enemies and enemy hero',
      'sharpshooter': 'Deal 6 damage to target creature',
    },
    flavorText: 'Call in the big guns.',
    set: 'base',
  },
  {
    name: 'Combat Stims',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    cost: 1,
    effect: '+1/+1',
    effectCode: 'COMBAT_STIMS',
    heroEffects: {
      'bio-healer': '+2/+2 and regenerate 1 HP per turn',
      'tank-brute': '+1/+3',
    },
    flavorText: 'Instant boost.',
    set: 'base',
  },
  {
    name: 'Tech Upgrade',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    cost: 2,
    effect: '+2/+1',
    effectCode: 'TECH_UPGRADE',
    heroEffects: {
      'drone-master': '+1/+1 and when equipped creature attacks, summon a 1/1 Drone',
      'sharpshooter': '+3/+0 and First Strike',
    },
    flavorText: 'Better, faster, stronger.',
    set: 'base',
  },
];

// Validate we have exactly 50 cards
if (CARDS.length !== 50) {
  throw new Error(`Expected 50 cards, got ${CARDS.length}`);
}

// Count by rarity
const rarityCounts = CARDS.reduce((acc, card) => {
  acc[card.rarity] = (acc[card.rarity] || 0) + 1;
  return acc;
}, {} as Record<string, number>);

console.log('Card Distribution:', rarityCounts);
// Expected: { COMMON: 25, RARE: 15, EPIC: 7, LEGENDARY: 3 }
